title: Freight Glossary
email: maxheinritz@gmail.com
description: >-
  A collection of freight logistics terms and definitions.
domain: freightglossary.com
url: https://freightglossary.com
github_username:  maxh

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
